### ISSUE TITLE
UST-EASY does not seem to put an important global value set for country into scratch orgs using it

### ISSUE THREAD

**Issue by ustkgh** [UniversityOfSaintThomas/UST-EASY#21]
When including `version_id: '04t4P000002KnQuQAK'` as a dependency in the `cumulusci.yml` of a greenfield repository and running `cci flow run dev_org` against that greenfield repository, installing `04t4P000002KnQuQAK` errors out with the following complaint:

```
Error: (Family__c.Birth_Country_Region_Territory__c) The global picklist cannot be resolved, Details: Family__c.Birth_Country_Region_Territory__c: The global picklist cannot be resolved

(Family__c.Parent_Guardian) Global value set 'Birth_Country_Region_Territory__c' in record type 'Parent/Guardian' on the entity 'Family__c' cannot be resolved, Details: 

Family__c.Parent_Guardian: Global value set 'Birth_Country_Region_Territory__c' in record type 'Parent/Guardian' on the entity 'Family__c' cannot be resolved
```

This is low-priority.  User story is:

> If I were making a greenfield "counselor assignment" repository, it should probably be a standalone repo, since it's a highly modularizable piece of business logic that, in theory, could simply be taken out of an org if Admissions ever changed their minds about wanting it.
> 
> The larger UST Salesforce org would still be just fine without my "counselor assignment" code (other than counselors not getting auto-assigned anymore).
> 
> The Apex classes in a "counselor assignment" repo may need to refer to certain UST-specific fields that fall within the scope of "UST-EASY," trusting that they will exist.
> 
> However, the "counselor assignment" repo shouldn't have the definitions of those fields within its codebase.

At the moment, I have not tried setting up [my greenfield repo](https://github.com/UniversityOfSaintThomas/UST-EASY-dependency-example) to be an "unlocked org-dependent package."  It is just a vanilla folder on my desktop with a couple of CCI-related and SFDX-related configuration files in it, as well as a single Apex class.

```yaml
minimum_cumulusci_version: '3.51.1'
project:
    name: UST-EASY-dependency-example
    package:
        name: UST-EASY-dependency-example
        api_version: '53.0'
    dependencies:
        - github: 'https://github.com/SalesforceFoundation/EDA' # Maybe not actually necessary for this codebase
        - version_id: '04t4P000002KnQuQAK' # UST-EASY
        - version_id: '04t5b000002BOz0AAG' # UST-Utils
    git:
        default_branch: 'main'
    source_format: sfdx
```
